/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ifes.poo2.xadrez.GUI.model.splitPane;

import java.awt.Component;
import ifes.poo2.xadrez.GUI.model.messagePane.MessagePane;
import ifes.poo2.xadrez.GUI.model.table.TableFactory;

/**
 *
 * @author pdr
 */
public class SplitPane extends javax.swing.JPanel {
        private Component[] components = new Component[2];
        /**
         * Creates new form MainView
         */
        public SplitPane(Component left, Component right) {
                components[0]= left;
                components[1] = right;
                initComponents();
                splitPane.setEnabled(false);
                //splitPane.setLeftComponent(TableFactory.createTable());
                //splitPane.setRightComponent(new MessagePane());
                splitPane.setLeftComponent(left);
                splitPane.setRightComponent(right);
                

        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                splitPane = new javax.swing.JSplitPane();

                setLayout(new java.awt.GridLayout(1, 0));

                splitPane.setDividerLocation(480);
                splitPane.setDividerSize(2);
                add(splitPane);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JSplitPane splitPane;
        // End of variables declaration//GEN-END:variables

        /**
         * @return the components
         */
        
        public Component[] getSplitComponents() {
                return components;
        }
        
        /**
         * @return the left Component
         */
        public Component getLeftSplitComponents() {
                return getSplitComponentPos(0);
        }
        
        /**
         * @return the right Component
         */
        public Component getRightSplitComponent() {
                return getSplitComponentPos(1);
        }
        public Component getSplitComponentPos(int i){
                return components[i];
        }
        

       
        
}
