package ifes.poo2.xadrez.GUI.model.mainFrame;


import java.awt.Color;
import javax.swing.JTextField;
import ifes.poo2.xadrez.GUI.model.mainPanel.MainPanel;
import ifes.poo2.xadrez.GUI.model.messagePane.MessagePane;
import ifes.poo2.xadrez.GUI.model.splitPane.SplitPane;
import ifes.poo2.xadrez.GUI.model.splitPane.SplitPaneFactory;
import ifes.poo2.xadrez.GUI.model.table.LineFactory;
import ifes.poo2.xadrez.GUI.model.table.ChessTable;
import ifes.poo2.xadrez.GUI.model.table.TableFactory;
import ifes.poo2.xadrez.GUI.model.textBar.TextBar;
import ifes.poo2.xadrez.GUI.model.table.Tile;
import ifes.poo2.xadrez.GUI.model.table.TileFactory;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pdr
 */
public class MainFrame extends javax.swing.JFrame {

        public static MainFrame create() {
                return new MainFrame(); //To change body of generated methods, choose Tools | Templates.
        }

        
        private MainPanel mainPanel = MainPanel.create();
        /**
         * Creates new form JFrame
         */
        public MainFrame() {
                initComponents();
                getContentPane().add(mainPanel);
                revalidate();
                pack();       
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                topMenu = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jMenu2 = new javax.swing.JMenu();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.GridLayout(1, 0));

                jMenu1.setText("File");
                topMenu.add(jMenu1);

                jMenu2.setText("Edit");
                topMenu.add(jMenu2);

                setJMenuBar(topMenu);

                pack();
        }// </editor-fold>//GEN-END:initComponents
        
        /**
         * @param args the command line arguments
         */
     
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenuBar topMenu;
        // End of variables declaration//GEN-END:variables

        /**
         * @return the mainPanel
         */
        public MainPanel getMainPanel() {
                return mainPanel;
        }

        /**
         * @param mainPanel the mainPanel to set
         */
        public void setMainPanel(MainPanel mainPanel) {
                this.mainPanel = mainPanel;
        }
        
        public ChessTable getChessTable(){
                return (ChessTable) getMainPanel().getSplitPane().getLeftSplitComponents();
        }
        
        public JTextField getTextField(){
                return getMainPanel().getTextBar().getTextField();
        }
        
        public MessagePane getMessagePane(){
                return (MessagePane) getMainPanel().getSplitPane().getRightSplitComponent();
        }
}
