package ifes.poo2.xadrez.GUI.model.messagePane;

import ifes.poo1.xadrez.model.cdp.constantes.Cores;
import ifes.poo1.xadrez.model.cdp.jogador.Jogador;

/**
 *
 * @author cthulhu
 */
public class StatusBar extends javax.swing.JPanel {

        /**
         * Creates new form StatusBar
         */
        private static StatusBar statusBar = null;
        
        public static StatusBar getInstanceOf(){
                if (statusBar == null) {
                       statusBar = new StatusBar();
                }
                return statusBar;
        }
        private StatusBar() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                jPanel1 = new javax.swing.JPanel();
                vezLabel = new javax.swing.JLabel();
                nomeLabel = new javax.swing.JLabel();
                cor = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                placar = new javax.swing.JLabel();
                brancoLabel = new javax.swing.JLabel();
                brancoPontLabel = new javax.swing.JLabel();
                pretoLabel = new javax.swing.JLabel();
                pretoPontLabel = new javax.swing.JLabel();

                setLayout(new java.awt.GridBagLayout());

                jPanel1.setLayout(new java.awt.GridBagLayout());

                vezLabel.setText("Vez:");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
                jPanel1.add(vezLabel, gridBagConstraints);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
                jPanel1.add(nomeLabel, gridBagConstraints);
                jPanel1.add(cor, new java.awt.GridBagConstraints());

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                add(jPanel1, gridBagConstraints);

                jPanel2.setLayout(new java.awt.GridBagLayout());

                placar.setText("Placar:");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
                jPanel2.add(placar, gridBagConstraints);

                brancoLabel.setText("Branco:");
                jPanel2.add(brancoLabel, new java.awt.GridBagConstraints());
                jPanel2.add(brancoPontLabel, new java.awt.GridBagConstraints());

                pretoLabel.setText("Preto:");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 0);
                jPanel2.add(pretoLabel, gridBagConstraints);
                jPanel2.add(pretoPontLabel, new java.awt.GridBagConstraints());

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                add(jPanel2, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        
        
        public static void setVez(Jogador jogador){
                cor.setText(jogador.getCor().toString());
                nomeLabel.setText(jogador.getNome());
        }
        
        public static void setPontuacao(Jogador jogador){
                String pont = ""+jogador.getPontuacao();
                
                if (jogador.getCor() == Cores.branco)  brancoPontLabel.setText(pont);
                else pretoPontLabel.setText(pont);
        }
        
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel brancoLabel;
        private static javax.swing.JLabel brancoPontLabel;
        private static javax.swing.JLabel cor;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private static javax.swing.JLabel nomeLabel;
        private javax.swing.JLabel placar;
        private javax.swing.JLabel pretoLabel;
        private static javax.swing.JLabel pretoPontLabel;
        private javax.swing.JLabel vezLabel;
        // End of variables declaration//GEN-END:variables
}
