/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ifes.poo2.xadrez.GUI.model.table;

/**
 *
 * @author pdr
 */
public class ChessTable extends javax.swing.JPanel {
        private Line[] lines = new Line[8];
        private static ChessTable table = null;
        /**
         * Creates new form Table
         */
        private ChessTable() {
                initComponents();
        }
        
        public static ChessTable getInstanceOf(){
                if (table == null){
                        table = new ChessTable();
                        table.setComponents();
                }
                
                return table;
        }
        
        private void setComponents(){
                table.setLayout(new java.awt.GridLayout(0, 1));
                int index;
                for (index=0; index<8; index++){
                        if (index%2 == 0) lines[index] =LineFactory.createEvenLine();
                        else lines[index] = LineFactory.createOddLine();
                        table.add(lines[index]);
                }
        }
        
        

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        
        
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setLayout(new java.awt.GridLayout(0, 1));
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables

        /**
         * @return the lines
         */
        public Line[] getLines() {
                return lines;
        }

        /**
         * @param lines the lines to set
         */
        public void setLines(Line[] lines) {
                this.lines = lines;
        }
        
        public Tile getPosicao(ifes.poo2.xadrez.GUI.model.table.Posicao pos){        
                return lines[pos.getLinha()].getTile(pos.getColuna());
        }
}
