package ifes.poo2.xadrez.GUI.model.table;

import ifes.poo1.xadrez.model.cdp.constantes.Cores;
import ifes.poo1.xadrez.model.cdp.constantes.NomePecas;
import ifes.poo2.xadrez.GUI.pecaView.PecaView;
import java.awt.Color;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pdr
 */
public class Tile extends javax.swing.JPanel {
        
        private Color originalColor;
        
        /**
         * Creates new form Tile
         */
        public Tile() {
                initComponents();
                originalColor = getBackground();
                  
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setBackground(new java.awt.Color(206, 148, 0));
                setMaximumSize(new java.awt.Dimension(300, 300));
                setMinimumSize(new java.awt.Dimension(300, 300));
                setPreferredSize(new java.awt.Dimension(100, 100));
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                formMouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                formMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                formMouseReleased(evt);
                        }
                });
                setLayout(new java.awt.BorderLayout());
        }// </editor-fold>//GEN-END:initComponents

        private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
                JLabel pic = new PecaView(ifes.poo1.xadrez.model.cdp.constantes.NomePecas.Cavalo, ifes.poo1.xadrez.model.cdp.constantes.Cores.branco);
                add(pic);
                revalidate();
                repaint();
        }//GEN-LAST:event_formMouseClicked

        private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
                //setOriginalColor();
                
        }//GEN-LAST:event_formMouseReleased

        private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
               // setColor(Color.GREEN);
                JLabel pic = new PecaView(ifes.poo1.xadrez.model.cdp.constantes.NomePecas.Cavalo, ifes.poo1.xadrez.model.cdp.constantes.Cores.branco);
                this.add(pic);
                this.revalidate();
                this.repaint();
        }//GEN-LAST:event_formMousePressed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
        
        public void setColor(Color color){
                this.setBackground(color);
                this.revalidate();
                this.repaint();
        }
        
        public void setOriginalColor(){
                this.setBackground(originalColor);
                this.revalidate();
                this.repaint();
        }
        
        /**
         * @return the originalColor
         */
        public Color getOriginalColor() {
                return originalColor;
        }

        /**
         * @param originalColor the originalColor to set
         */
        public void setOriginalColor(Color originalColor) {
                this.originalColor = originalColor;
        }
        
         public void addPecaView(PecaView pv){
                add(pv);
                revalidate();
                repaint();
        }
        
       

}
